# #Указание основы образа (python) через FROM
# FROM python:alpine
# #Указание описания и/или иных метаданных
# LABEL info = "Шаповалов, третья практическая"
# #Указание рабочей директории проекта
# WORKDIR C:\Users\Admin\Desktop\Python\PW_KC
# #COPY копирует наш материал из хост - системы 
# COPY PR3_KC.py C:\Users\Admin\Desktop\Python\PW_KC
# #Через CMD добавляем образ в Docker
# CMD ["python", "PR3_KC.py"]

# FROM nginx:alpine
# COPY index.html C:\Users\Admin\Desktop\Python\PW_KC
# #Объявление рабочего порта
# EXPOSE 42

# FROM python:alpine
# WORKDIR C:\Users\Admin\Desktop\Python\PW_KC\calc-py
# COPY calc.py C:\Users\Admin\Desktop\Python\PW_KC\calc-py
# CMD ["python", "calc.py"]

# FROM python:alpine
# WORKDIR C:\Users\Admin\Desktop\Python\PW_KC\calc-java
# COPY calc.java C:\Users\Admin\Desktop\Python\PW_KC\calc-java
# CMD ["python", "calc.java"]